# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d8ae4574e960c3c4451f1516bde2d2b8fb701c1d41e117c5f7675110a8858c47c9d897ad53991dbc42d5c0392ef115361f3842a2b83e54300cd5f9f7a8b43579

test:
  secret_key_base: caf95de3b2b91aed0f7334370751a4f3293a1d3b6fc7cf8849a909e3f9905ac73c1fb5c096f847f0fbdd2dc190e15cfe421d4c7ccf8ade5f59d9746c1c996168

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
